from PIL import Image
import imagehash, os, sys

print("Flagpole")
userFlagDir = str(input("Enter the directory that stores your flags > "))
userInput = str(input("Enter the path to the flag you want to test > "))
try:
    userHash = imagehash.average_hash(Image.open(userInput))
except:
    print("Invalid File - Must be a local file path")
    exit()

def image(x):
    if sys.platform.lower() == "win32":
        return userHash - imagehash.average_hash(Image.open(userFlagDir + "\\" + x + ".png")),
    else:
        return userHash - imagehash.average_hash(Image.open(userFlagDir + "/" + x + ".png")),

countries = {
                "Abkhazia": image("Abkhazia"),
                "Afghanistan": image("Afghanistan"),
                "Albania": image("Albania"),
                "Algeria": image("Algeria"),
                "Andorra": image("Andorra"),
                "Angola": image("Angola"),
                "Antigua and Barbuda": image("Antigua and Barbuda"),
                "Argentina": image("Argentina"),
                "Armenia": image("Armenia"),
                "Artsakh": image("Artsakh"),
                "Australia": image("Australia"),
                "Austria": image("Austria"),
                "Azerbaijan": image("Azerbaijan"),
                "Bahamas": image("Bahamas"),
                "Bahrain": image("Bahrain"),
                "Bangladesh": image("Bangladesh"),
                "Barbados": image("Barbados"),
                "Belarus": image("Belarus"),
                "Belgium": image("Belgium"),
                "Belize": image("Belize"),
                "Benin": image("Benin"),
                "Bhutan": image("Bhutan"),
                "Bolivia": image("Bolivia"),
                "Bosnia and Herzegovina": image("Bosnia and Herzegovina"),
                "Botswana": image("Botswana"),
                "Brazil": image("Brazil"),
                "Brunei": image("Brunei"),
                "Bulgaria": image("Bulgaria"),
                "Burkina Faso": image("Burkina Faso"),
                "Burundi": image("Burundi"),
                "Cambodia": image("Cambodia"),
                "Cameroon": image("Cameroon"),
                "Canada": image("Canada"),
                "Cape Verde": image("Cape Verde"),
                "Central African Republic": image("Central African Republic"),
                "Chad": image("Chad"),
                "Chile": image("Chile"),
                "China": image("China"),
                "Colombia": image("Colombia"),
                "Comoros": image("Comoros"),
                "Cook Islands": image("Cook Islands"),
                "Costa Rica": image("Costa Rica"),
                "Croatia": image("Croatia"),
                "Cuba": image("Cuba"),
                "Cyprus": image("Cyprus"),
                "Czech Republic": image("Czech Republic"),
                "Democratic Republic of the Congo": image("Democratic Republic of the Congo"),
                "Denmark": image("Denmark"),
                "Djibouti": image("Djibouti"),
                "Dominica": image("Dominica"),
                "Dominican Republic": image("Dominican Republic"),
                "East Timor": image("East Timor"),
                "Ecuador": image("Ecuador"),
                "Egypt": image("Egypt"),
                "El Salvador": image("El Salvador"),
                "Equatorial Guinea": image("Equatorial Guinea"),
                "Eritrea": image("Eritrea"),
                "Estonia": image("Estonia"),
                "Ethiopia": image("Ethiopia"),
                "Federated States of Micronesia": image("Federated States of Micronesia"),
                "Fiji": image("Fiji"),
                "Finland": image("Finland"),
                "Flagpole": image("Flagpole"),
                "France": image("France"),
                "Gabon": image("Gabon"),
                "Gambia": image("Gambia"),
                "Georgia": image("Georgia"),
                "Georgia": image("Georgia"),
                "Germany": image("Germany"),
                "Ghana": image("Ghana"),
                "Greece": image("Greece"),
                "Grenada": image("Grenada"),
                "Guatemala": image("Guatemala"),
                "Guinea": image("Guinea"),
                "Guinea-Bissau": image("Guinea-Bissau"),
                "Guyana": image("Guyana"),
                "Haiti": image("Haiti"),
                "Honduras": image("Honduras"),
                "Hungary": image("Hungary"),
                "Iceland": image("Iceland"),
                "India": image("India"),
                "Indonesia": image("Indonesia"),
                "Iran": image("Iran"),
                "Iraq": image("Iraq"),
                "Ireland": image("Ireland"),
                "Israel": image("Israel"),
                "Italy": image("Italy"),
                "Ivory Coast": image("Ivory Coast"),
                "Jamaica": image("Jamaica"),
                "Japan": image("Japan"),
                "Jordan": image("Jordan"),
                "Kazakhstan": image("Kazakhstan"),
                "Kenya": image("Kenya"),
                "Kiribati": image("Kiribati"),
                "Kosovo": image("Kosovo"),
                "Kuwait": image("Kuwait"),
                "Kyrgyzstan": image("Kyrgyzstan"),
                "Laos": image("Laos"),
                "Latvia": image("Latvia"),
                "Lebanon": image("Lebanon"),
                "Lesotho": image("Lesotho"),
                "Liberia": image("Liberia"),
                "Libya": image("Libya"),
                "Liechtenstein": image("Liechtenstein"),
                "Lithuania": image("Lithuania"),
                "Luxembourg": image("Luxembourg"),
                "Madagascar": image("Madagascar"),
                "Malawi": image("Malawi"),
                "Malaysia": image("Malaysia"),
                "Maldives": image("Maldives"),
                "Mali": image("Mali"),
                "Malta": image("Malta"),
                "Marshall Islands": image("Marshall Islands"),
                "Mauritania": image("Mauritania"),
                "Mauritius": image("Mauritius"),
                "Mexico": image("Mexico"),
                "Moldova": image("Moldova"),
                "Monaco": image("Monaco"),
                "Mongolia": image("Mongolia"),
                "Montenegro": image("Montenegro"),
                "Morocco": image("Morocco"),
                "Mozambique": image("Mozambique"),
                "Myanmar": image("Myanmar"),
                "Namibia": image("Namibia"),
                "Nauru": image("Nauru"),
                "Nepal": image("Nepal"),
                "Netherlands": image("Netherlands"),
                "New Zealand": image("New Zealand"),
                "Nicaragua": image("Nicaragua"),
                "Niger": image("Niger"),
                "Nigeria": image("Nigeria"),
                "Niue": image("Niue"),
                "North Korea": image("North Korea"),
                "North Macedonia": image("North Macedonia"),
                "Norway": image("Norway"),
                "Oman": image("Oman"),
                "Pakistan": image("Pakistan"),
                "Palau": image("Palau"),
                "Panama": image("Panama"),
                "Papua New Guinea": image("Papua New Guinea"),
                "Paraguay": image("Paraguay"),
                "Peru": image("Peru"),
                "Philippines": image("Philippines"),
                "Poland": image("Poland"),
                "Portugal": image("Portugal"),
                "Qatar": image("Qatar"),
                "Republic of the Congo": image("Republic of the Congo"),
                "Romania": image("Romania"),
                "Russia": image("Russia"),
                "Rwanda": image("Rwanda"),
                "Sahrawi Arab Democratic Republic": image("Sahrawi Arab Democratic Republic"),
                "Saint Kitts and Nevis": image("Saint Kitts and Nevis"),
                "Saint Lucia": image("Saint Lucia"),
                "Saint Vincent and the Grenadines": image("Saint Vincent and the Grenadines"),
                "Samoa": image("Samoa"),
                "San Marino": image("San Marino"),
                "Sao Tome and Principe": image("Sao Tome and Principe"),
                "Saudi Arabia": image("Saudi Arabia"),
                "Senegal": image("Senegal"),
                "Serbia": image("Serbia"),
                "Seychelles": image("Seychelles"),
                "Sierra Leone": image("Sierra Leone"),
                "Singapore": image("Singapore"),
                "Slovakia": image("Slovakia"),
                "Slovenia": image("Slovenia"),
                "Solomon Islands": image("Solomon Islands"),
                "Somalia": image("Somalia"),
                "Somaliland": image("Somaliland"),
                "South Africa": image("South Africa"),
                "South Korea": image("South Korea"),
                "South Ossetia": image("South Ossetia"),
                "South Sudan": image("South Sudan"),
                "Spain": image("Spain"),
                "Sri Lanka": image("Sri Lanka"),
                "State of Palestine": image("State of Palestine"),
                "Sudan": image("Sudan"),
                "Suriname": image("Suriname"),
                "Swaziland": image("Swaziland"),
                "Sweden": image("Sweden"),
                "Switzerland": image("Switzerland"),
                "Syria": image("Syria"),
                "Taiwan": image("Taiwan"),
                "Tajikistan": image("Tajikistan"),
                "Tanzania": image("Tanzania"),
                "Thailand": image("Thailand"),
                "Togo": image("Togo"),
                "Tonga": image("Tonga"),
                "Transnistria": image("Transnistria"),
                "Trinidad and Tobago": image("Trinidad and Tobago"),
                "Tunisia": image("Tunisia"),
                "Turkey": image("Turkey"),
                "Turkish Republic of Northern Cyprus": image("Turkish Republic of Northern Cyprus"),
                "Turkmenistan": image("Turkmenistan"),
                "Tuvalu": image("Tuvalu"),
                "Uganda": image("Uganda"),
                "Ukraine": image("Ukraine"),
                "United Arab Emirates": image("United Arab Emirates"),
                "United Kingdom": image("United Kingdom"),
                "United States of America": image("United States of America"),
                "Uruguay": image("Uruguay"),
                "Uzbekistan": image("Uzbekistan"),
                "Vanuatu": image("Vanuatu"),
                "Vatican City": image("Vatican City"),
                "Venezuela": image("Venezuela"),
                "Vietnam": image("Vietnam"),
                "Yemen": image("Yemen"),
                "Zambia": image("Zambia"),
                "Zimbabwe": image("Zimbabwe"),
            }

def minimum():
    for i in [k for k,v in countries.items() if v == countries[min(countries, key=countries.get)]]:
        print("Looks Like:", i)
print("Calculating...")
minimum()
print("Similarity:", countries[min(countries, key=countries.get)][0], "(where 0 is identical)")
x = input("Do you want to show all the countries similarity (y/n)? > ")
if x == "y":
    if sys.platform.lower() == "win32":
        os.system('color')
    print("")
    y = []
    for i in countries.keys():
        y.append(i)
    z = 0
    for i in countries.values():
        print("\033[1;31m", y[z], "\033[1;36m - \033[1;34m", i[0], sep="")
        z += 1
    print("\033[0;0m")
input()